name: Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - 'nix flake check --accept-flake-config'
          - 'nix run nixpkgs#alejandra -- -c . -e ./npins'
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - run: ${{ matrix.command }}
